default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  tags: [werf] 
 
variables:
    IMAGE_NAME: "reg.pit.protei.ru/safe-city/integration-service"
    IMAGE_TAG: "latest"
    COMPOSE_FILE: "docker-swarm.yml"
    COMPOSE_PROJECT_NAME: "integration-service"

stages:
  - build 
  - build-sonar
  - deploy

build-prod:
  image: docker:latest
  stage: build
  before_script:
    - docker context use default
  script:
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
    - docker image ls

    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" "$HARBOR_HOST"
    - docker push "$IMAGE_NAME":"$IMAGE_TAG"
    - docker rmi "$IMAGE_NAME":"$IMAGE_TAG"
 # rules:
 #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
 #     when: always
 #   - when: never

deploy_swarm:
  stage: deploy
  before_script:
    - docker context use swarm-dev
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" "$HARBOR_HOST"
  script:  
    - docker pull "$IMAGE_NAME":"$IMAGE_TAG"
    - docker stack deploy -c $COMPOSE_FILE $COMPOSE_PROJECT_NAME --with-registry-auth
    - docker context use default
  #rules:
  #  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  #    when: always
  #  - when: never