
version: '3.8'

services:
  slow-light-gate:
    image: reg.pit.protei.ru/safe-city/integration-service:latest
    ports:
      - "6007:80"
      #- "6008:443"#
      #- "6009:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      #- ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
    configs:
      - source: gate_config
        target: gate-config.json
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == worker
    networks:
      - slow-light-overlay

networks:
  slow-light-overlay:
    driver: overlay
    attachable: true

configs:
  gate_config:
    external: true
