
version: '3.8'

services:
  slow-light-gate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./gate-config.json:/app/gate-config.json:ro
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - slow-light-network

networks:
  slow-light-network:
    driver: bridge

configs:
  gate_config:
    external: true
